version: '3'
services:
  # container for postgres
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_PASSWORD=postgres_password
  # container for redis
  redis:
    image: "redis:latest"
  # nginx
  nginx: 
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx 
    ports: 
      - '3050:80'
  # container for the server
  api:
    build:
      dockerfile: Dockerfile.dev 
      context: ./server #look in this directory for the dockerfile
    volumes: 
      - /app/node_modules
      - ./server:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  # container for client
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
    environment:
      - WDS_SOCKET_PORT=0 
  # container for worker 
  worker:
    build: 
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
      - /app/node_modules
      - ./worker:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379